# শুধুমাত্র এই নির্দিষ্ট ফিচার ব্রাঞ্চে পুশ করলে এটি চলবে
on:
  push:
    branches:
      - 'feature/keyvault-test'

permissions:
  contents: read

jobs:
  deploy-kv:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend-config="key=test-kv.tfstate"

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve
